name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: install devenv
        run: nix profile install nixpkgs#devenv
      - uses: Swatinem/rust-cache@v2
      - name: test the app
        run: devenv shell test-app
      - uses: actions/upload-artifact@v4
        with:
          name: rustpolnak
          path: target/release/rustpolnak
          if-no-files-found: error
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/rustpolnak
